name: release

on:
  push:
    branches:
      - "master"
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: generate Docker image tags
        id: generate_tags
        run: |

          if [[ $GITHUB_REF_TYPE == "tag" ]]; then
            TAGS="orbatschow/dhcpd:latest,orbatschow/dhcpd:$(echo $GITHUB_REF_NAME | sed 's/[^a-zA-Z0-9_.-]/-/g' | sed -e 's/^v//')"
          else
            TAGS="orbatschow/dhcpd:latest"
          fi

          echo '::set-output name=tags::'${TAGS}

      - name: login to DockerHub
        uses: docker/login-action@v1
        with:
          username: orbatschow
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6
          push: true
          tags: ${{ steps.generate_tags.outputs.tags }}
